### ISSUE TITLE
Test uitkomsten

### ISSUE THREAD

**Issue by releaznl** [releaznl/releaz-project-manager#10]
- Je ziet niet wat verplicht veld is
- De 250 euro komt te laat
- prijzen overzicht laatste pagina en mail is niet echt duidelijk wanneer je nou wat moet betalen. Is het en 600 en maandelijks of hoe werkt het
- geen doorlink na bevestiging
- iphone maakt van het telefoonnummer een blauwe link in de mail (google inbox)
- de mouse overs bij vraagteken (?) bij oa socialmedia service is wat smal en hoog
- Tekst in de mail: 'bedankt voor aanvraag project' moet offerte zijn denk ik?
- bij uploaden huisstijl moet nog even wat meer info staan (wat bedoel je hiermee)
- Teksten allemaal richten op je ipv u? Lekker vlot? Of is dat too much?
- Juiste telefoonnummer van kees ipv releaznummer
- kleur van de tekst daarboven 'kom je er niet uit en heb je vragen' is slecht leesbaar

**Comment by releaz** [comment]
model_tooltip kan met css niet groter

**Comment by releaznl** [comment]
form div.required label.control-label:after {
  content:" * ";
  color:red;
}
